version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: todo-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

  # Backend API
  backend:
    build: ./Backend
    container_name: todo-backend
    restart: unless-stopped
    environment:
      - MONGODB_DB_URI=mongodb://admin:password@mongodb:27017/todo_db?authSource=admin
      - MONGODB_DB_NAME=todo_db
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - todo-network

  # Frontend React App
  frontend:
    build: ./Frontend
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge 